[sniffer]
file_path = "/home/gnb/iq_datawithtraffic.fc32"
sample_rate = 23040000
frequency = 1842500000
nid_1 = 1
ssb_numerology = 0
#rf_args = "type=b200,master_clock_rate=23.04e6"


[[pdcch]]
coreset_id = 1
subcarrier_offset = 426
num_prbs = 30
numerology = 0
dci_sizes_list = [41]
scrambling_id_start = 1
scrambling_id_end = 10
rnti_start = 17921
rnti_end = 17930
interleaving_pattern = "non-interleaved"
coreset_duration = 1
AL_corr_thresholds = [1, 0.5, 0.5, 1, 1]
num_candidates_per_AL = [0, 4, 4, 0, 0]
